### ISSUE TITLE
ninja: fatal: CreateProcess: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by fridapinto-debug** [darvincisec/DetectFrida#1]
while using your OLLVM its giving me ninja: fatal: CreateProcess: %1 is not a valid Win32 application.
I am on 64 bit windows 10 how to solve the error?

**Comment by darvincisec** [comment]
Can you refer to https://holycall.tistory.com/330 for OLLVM installation in Windows. The ollvm binaries i have put in another repo is for mac os

**Comment by fridapinto-debug** [comment]
ok I will try


-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Mar 14, 2020, 15:52 by notifications@github.com:

**Comment by fridapinto-debug** [comment]
tried but failed can you make binaries with windows 10 so that I can use in android studio?

**Comment by darvincisec** [comment]
Refer CMakelists to build non-obfuscated builds. i have no way to generate the ollvm binary required for windows environment.
