### ISSUE TITLE
Is it possible to support arm64-v8a device? 

### ISSUE THREAD

**Issue by moosecow** [darvincisec/DetectFrida#10]
Galaxy S6 Edge Plus is not working.
My system is arm64-v8a.
Help me.
<img width="1440" alt="스크린샷 2021-04-02 오후 4 05 31" src="https://user-images.githubusercontent.com/29281469/113390845-7c6c8e80-93cd-11eb-8f29-2b87bb358ebb.png">

**Comment by fnazal18** [comment]
Did you add the NDK architecture filter in build.gradle? Like this. 

![imagen](https://user-images.githubusercontent.com/71537782/113538793-2274f000-95aa-11eb-837d-c9d6a0ce06fc.png)

**Comment by moosecow** [comment]
Yes, I added it.
I'll attach the error log below, please.

C/C++ Configuration Problem
native-lib | debug | arm64-v8a
Cannot run program "/Users/kim/Downloads/DetectFrida-master/app/src/main/c/../../../../../o-llvm-binary/ollvm-tll/build/bin_Darwin/clang" (in directory "/Users/kim/Downloads/DetectFrida-master/app/.cxx/cmake/debug/arm64-v8a"): error=2, No such file or directory

![스크린샷 2021-04-06 오전 12 13 01](https://user-images.githubusercontent.com/29281469/113589907-ea82b100-966c-11eb-9c2d-fddb1e7ff849.png)

**Comment by fnazal18** [comment]
Well, that's due to the absence of the obfuscator binaries. Remove it from the CMakeLists.txt and rebuild the project. Or you could use the obfuscator (ollvm-tll) by building it from the original project.

**Comment by moosecow** [comment]
Thank you for your kind explanation. I'll try again

**Comment by moosecow** [comment]
I compiled it by adding rollvm-tll. 
#include <stdbool.h>,
#include<asm/unistd.h>
Error is occurring, can you please let me know?



![스크린샷 2021-04-06 오전 12 13 01](https://user-images.githubusercontent.com/29281469/113861093-c72d4280-97e1-11eb-9670-affbe01b14eb.png)
