### ISSUE TITLE
native crash

### ISSUE THREAD

**Issue by IceDcap** [darvincisec/DetectFrida#15]
![image](https://user-images.githubusercontent.com/5344957/122200858-0527a080-cece-11eb-889b-288c0353746e.png)
![image](https://user-images.githubusercontent.com/5344957/122201110-41f39780-cece-11eb-91a1-96e2c0c72857.png)
![image](https://user-images.githubusercontent.com/5344957/122200521-b5e17000-cecd-11eb-851f-e3105118ac0a.png)
![image](https://user-images.githubusercontent.com/5344957/122200682-da3d4c80-cecd-11eb-804d-84b7a7259978.png)

**Comment by darvincisec** [comment]
Are you able to reproduce this issue with the apk provided in this repo? If yes, can you share the logs specific for this application

**Comment by IceDcap** [comment]
> Are you able to reproduce this issue with the apk provided in this repo? If yes, can you share the logs specific for this application

It's hard to reproduce, but i will try it.
Do you think about that reading buffer from the address provided in maps will out of bounds by the length from origin elf's segment.

**Comment by darvincisec** [comment]
From Android 10 onwards, maps contains libc addresses in segmented fashion. Changes are made in a generic fashion to address this.  Looks like there is a need to put some more protection before calculating the checksum.

**Comment by darvincisec** [comment]
are you able to reproduce with this project?

**Comment by IceDcap** [comment]
> are you able to reproduce with this project?

Sorry, I can't reproduce it from my devices.
