### ISSUE TITLE
take to long compile time with llvm option -mllvm -bcf

### ISSUE THREAD

**Issue by surbiks** [darvincisec/DetectFrida#16]
hi
use llvm `-mllvm -bcf` take long over 15 min to compile source code. 
use ubuntu 20.04 and compiled o-llvm from source code for Linux.

**Comment by darvincisec** [comment]
Thats strange. Though I havent used the linux version, but still it should not take much time. Did you try on Mac OS ? 
I am not sure if I can resolve anything on my side

**Comment by surbiks** [comment]
hello
sorry, I can't test in  Mac OS. 
project is correct, the problem is o-llvm in Linux because other samples and new projects take a long time to compile.

thanks

**Comment by darvincisec** [comment]
I am closing this as it is more related to the obfuscation tool which i dont have control on.
