### ISSUE TITLE
Frida detect correctly, but permit using the app yet

### ISSUE THREAD

**Issue by cesarwillymc** [darvincisec/DetectFrida#29]
Do you have some code for kill the app when detect frida ? 
Thank you.

**Comment by darvincisec** [comment]
For killing the app, refer to code snippets in my other project [AntidebugandMemoryDump ](https://github.com/darvincisec/AntiDebugandMemoryDump/blob/847e4cfacb14c2061ef2e122e74274bd13292388/app/src/main/c/native-lib.c#LL314C19-L314C24)
