### ISSUE TITLE
How to check in Activity 

### ISSUE THREAD

**Issue by Karthik-hb** [darvincisec/DetectFrida#37]
How to check is app detected frida or not in mainactivity.
It will helpfull if you create native method and assign values if it is detect frida and use that in actvity,

**Comment by ShankarKakumani** [comment]
how did you close this?
did you have a example of how this can be checked from activity  @Karthik-hb ?

**Comment by Karthik-hb** [comment]
Yes,

Please create method inside cpp and access it.
