### ISSUE TITLE
Disk To Memory Checks fail on Android 11, even if there isn't hooking framework

### ISSUE THREAD

**Issue by MahmoudElFerekh** [darvincisec/DetectFrida#4]
Although there isn't any hooking framework invoked, when trying the library code on Android 11, this is being executed:
__android_log_print(ANDROID_LOG_WARN, APPNAME, "Executable Section Manipulated, "
                                                               "maybe due to Frida or other hooking framework."
                                                               "Act Now!!!");
(native-lib.c file, line 195)

This false alert is only happening on Android 11.

**Comment by darvincisec** [comment]
Thanks for reporting. I will look into it for a fix

**Comment by Marechal-L** [comment]
Hi @darvincisec, 
I encounter this issue everytime on a Google Pixel 4a running Android 11. 
Let me know if you need further information to fix this issue.

**Comment by darvincisec** [comment]
I can reproduce this issue on my side..i can see what is going wrong, just that i need to find time to fix it.

**Comment by darvincisec** [comment]
Refer [here](https://github.com/darvincisec/DetectFrida/commit/4f3b8311d312a9e8a947c73f4de184d1b3a8bc74) for the fixes
